# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: formrec-invoice-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   host: invoice.local
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: invoice-formrec
#             port:
#               number: 5000
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: formrec-backend-ingress
#   annotations:
#     kubernetes.io/ingress.class: addon-http-application-routing
# spec:
#   rules:
#   - host: backend.formrec-co-containers-aks-19311b-73dbf973.hcp.eastus.azmk8s.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service: 
#             name: backend
#             port: 
#               number: 80