apiVersion: v1
kind: Service
metadata:
  name: {{ include "formrec.fullname" . }}
  labels:
    {{- include "formrec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5672
      protocol: TCP
      name: http
  selector:
    {{- include "formrec.selectorLabels" . | nindent 4 }}
